---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install
      - run: yarn lint
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DH_PASSWORD }}
          username: ${{ secrets.DH_USERNAME }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: jasondrhogent/webapp:latest